#!/usr/bin/env bash
# tools/install_git_hooks.sh — wire tools/secret_scan.sh into
# .git/hooks/pre-commit so every commit gets the staged-changes
# secret scan automatically.
#
# Idempotent: re-running just rewrites the hook. Safe to invoke
# from ./run.sh bootstrap or by hand. The hook itself is a thin
# shim that execs the version-controlled script, so future edits
# to tools/secret_scan.sh take effect with no re-install.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
hook_path="$repo_root/.git/hooks/pre-commit"

if [[ ! -d "$repo_root/.git" ]]; then
  echo "install_git_hooks: $repo_root is not a git working tree" >&2
  exit 2
fi

mkdir -p "$(dirname "$hook_path")"

cat > "$hook_path" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by tools/install_git_hooks.sh.
# Delegates to the version-controlled scanner so updates land
# without re-running the installer.
exec "$(git rev-parse --show-toplevel)/tools/secret_scan.sh" --staged
HOOK

chmod +x "$hook_path"
chmod +x "$repo_root/tools/secret_scan.sh"

echo "install_git_hooks: wrote $hook_path (delegates to tools/secret_scan.sh --staged)"
